# Generated by Django 6.0.4 on 2026-05-25 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('protocols', '0007_protocolexecutionstate_gate_warnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condicao_tratada_cid', models.CharField(blank=True, max_length=20, null=True)),
                ('ajustou_dose_sugerida', models.BooleanField(default=False)),
                ('motivo_ajuste', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_data', to='audit.auditlog')),
                ('execution_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_data', to='protocols.protocolexecutionstate')),
            ],
        ),
    ]
