# Generated by Django 6.0.4 on 2026-06-01 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('protocols', '0007_protocolexecutionstate_gate_warnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID do cliente para idempotência de envios offline.', null=True)),
                ('condicao_tratada_cid', models.CharField(blank=True, help_text='Código CID-10 da condição tratada (ex: J45.9).', max_length=20, null=True)),
                ('seguiu_protocolo_integralmente', models.BooleanField(blank=True, help_text='Null = não respondeu; True/False = resposta explícita.', null=True)),
                ('desfecho_esperado', models.CharField(blank=True, help_text='Desfecho clínico esperado informado pelo profissional.', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_response', to='audit.auditlog')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_response', to='protocols.protocolexecution')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('client_uuid',), name='unique_research_response_client_uuid')],
            },
        ),
    ]
