# Generated by Django 6.0.4 on 2026-06-09 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0003_notification_level_notification_scheduled_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='verb',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('recipient', 'target_content_type', 'target_object_id', 'title')},
        ),
    ]
