# Generated by Django 6.0.4 on 2026-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prescription', models.FloatField()),
                ('is_per_m2', models.BooleanField(default=False)),
                ('frequency_hours', models.IntegerField()),
                ('min_dose_mg_kg', models.FloatField()),
                ('max_dose_mg_kg', models.FloatField()),
                ('max_absolute_dose_mg', models.FloatField()),
                ('concentration_mg', models.FloatField()),
                ('concentration_ml', models.FloatField()),
                ('limits_by_age', models.JSONField()),
            ],
        ),
    ]
