# Generated by Django 6.0.4 on 2026-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='concentration_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='concentration_ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='limits_by_age',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='max_absolute_dose_mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='max_dose_mg_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='min_dose_mg_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
