# Generated by Django 6.0.4 on 2026-05-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medication_concentration_mg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.CharField(default='Outro', max_length=100),
        ),
        migrations.AddField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True, default='Nenhuma descrição disponível.'),
        ),
    ]
