# Generated by Django 6.0.4 on 2026-05-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medication_category_medication_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='is_per_m2',
        ),
    ]
