# Generated by Django 6.0.4 on 2026-05-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_remove_medication_is_per_m2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='concentration_mg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='concentration_ml',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='max_absolute_dose_mg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='max_dose_mg_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='min_dose_mg_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='prescription',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
