# Generated by Django 6.0.4 on 2026-05-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_alter_medication_concentration_mg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='adjustments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='administration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='contraindications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='indications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='overdose',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='presentations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='regimens',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
