# Generated by Django 6.0.4 on 2026-06-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_medication_adjustments_medication_administration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='frequency_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='prescription',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
