# Generated by Django 6.0.4 on 2026-05-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.PositiveIntegerField(blank=True, help_text='Altura em centímetros', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sintomas',
            field=models.ManyToManyField(blank=True, to='pacientes.sintoma'),
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
