# Generated by Django 6.0.4 on 2026-05-08 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='criado_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='pacientes.alergia'),
        ),
    ]
