# Generated by Django 6.0.4 on 2026-05-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_altura_paciente_peso_paciente_sintomas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['id']},
        ),
    ]
