# Generated by Django 6.0.4 on 2026-05-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
