# Generated by Django 6.0.4 on 2026-06-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_alta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da alta'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('alta', 'Alta')], db_index=True, default='ativo', max_length=10, verbose_name='Status'),
        ),
    ]
