# Generated by Django 6.0.4 on 2026-05-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arca_Ensina', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('medico', 'Médico'), ('admin', 'Administrador'), ('pesquisador', 'Pesquisador')], default='medico', max_length=20, verbose_name='Perfil'),
        ),
    ]
