# Generated by Django 6.0.4 on 2026-06-18 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_data_alta_paciente_status'),
        ('sedation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedationconversion',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente'),
        ),
    ]
