# Generated by Django 6.0.4 on 2026-05-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Medicamento')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('concentration', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Concentração')),
            ],
        ),
    ]
