# Generated by Django 6.0.4 on 2026-05-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
