# Generated by Django 6.0.4 on 2026-05-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0002_delete_medication'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('age_days', models.IntegerField(blank=True, null=True)),
                ('frequency_hours', models.IntegerField()),
                ('dose_total_mg', models.FloatField()),
                ('dose_per_dose_mg', models.FloatField()),
                ('volume_ml', models.FloatField(blank=True, null=True)),
                ('warnings', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medications.medication')),
            ],
        ),
    ]
