# Generated by Django 6.0.4 on 2026-05-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_calculator_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='dose_per_dose_mg',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='dose_total_mg',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='volume_ml',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='weight',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
