# Generated by Django 6.0.4 on 2026-05-06 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cid', models.CharField(blank=True, max_length=20, verbose_name='CID')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Autor')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('age_range_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade mínima (meses)')),
                ('age_range_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade máxima (meses)')),
                ('sex_applicable', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('A', 'Ambos')], default='A', max_length=1, verbose_name='Sexo aplicável')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Número da versão')),
                ('protocol_type', models.CharField(choices=[('guiado', 'Guiado'), ('painel', 'Painel')], db_index=True, default='guiado', max_length=10, verbose_name='Tipo de protocolo')),
                ('steps_data', models.JSONField(blank=True, default=dict, verbose_name='Dados de passos (guiado)')),
                ('panel_data', models.JSONField(blank=True, default=dict, verbose_name='Dados de painel')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(db_index=True, default=False, verbose_name='Versão atual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='protocols.protocol', verbose_name='Protocolo')),
            ],
            options={
                'verbose_name': 'Versão do Protocolo',
                'verbose_name_plural': 'Versões do Protocolo',
                'ordering': ['-version_number'],
                'constraints': [models.UniqueConstraint(fields=('protocol', 'version_number'), name='unique_protocol_version')],
            },
        ),
    ]
