# Generated by Django 6.0.4 on 2026-05-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='sex_applicable',
        ),
        migrations.AddField(
            model_name='protocol',
            name='gender_applicable',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], default=None, max_length=1, null=True, verbose_name='Gênero aplicável'),
        ),
    ]
