# Generated by Django 6.0.4 on 2026-05-10 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_remove_protocol_sex_applicable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Nome do paciente')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('abandonado', 'Abandonado')], db_index=True, default='em_andamento', max_length=15, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_executions', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='protocols.protocolversion', verbose_name='Versão do protocolo')),
            ],
            options={
                'verbose_name': 'Execução de Protocolo',
                'verbose_name_plural': 'Execuções de Protocolo',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('informativo', 'Informativo'), ('sim_nao', 'Sim/Não'), ('multipla_escolha', 'Múltipla Escolha'), ('checklist', 'Checklist com Regra de Avanço'), ('input_numerico', 'Input Numérico'), ('calculo_derivado', 'Cálculo Derivado'), ('prescricao', 'Prescrição de Medicação'), ('aguardar', 'Aguardar/Reavaliar'), ('loop_titulacao', 'Loop de Titulação')], max_length=20, verbose_name='Tipo do passo')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo / instrução')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_steps', to='protocols.protocolstep', verbose_name='Próximo passo padrão')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='protocols.protocolversion', verbose_name='Versão do protocolo')),
            ],
            options={
                'verbose_name': 'Passo do Protocolo',
                'verbose_name_plural': 'Passos do Protocolo',
                'ordering': ['version', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolExecutionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict, verbose_name='Valores informados / cálculos derivados')),
                ('loop_count', models.PositiveIntegerField(default=0, verbose_name='Contador de loop')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Respondido em')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='protocols.protocolexecution', verbose_name='Execução')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_states', to='protocols.protocolstep', verbose_name='Passo')),
            ],
            options={
                'verbose_name': 'Estado de Execução',
                'verbose_name_plural': 'Estados de Execução',
                'ordering': ['answered_at'],
            },
        ),
        migrations.AddField(
            model_name='protocolexecution',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_executions', to='protocols.protocolstep', verbose_name='Passo atual'),
        ),
        migrations.AddConstraint(
            model_name='protocolstep',
            constraint=models.UniqueConstraint(fields=('version', 'order'), name='unique_step_order_per_version'),
        ),
        migrations.AddConstraint(
            model_name='protocolexecutionstate',
            constraint=models.UniqueConstraint(fields=('execution', 'step'), name='unique_state_per_step_execution'),
        ),
    ]
