# Generated by Django 6.0.4 on 2026-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_protocolexecution_protocolstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolstep',
            name='step_type',
            field=models.CharField(choices=[('info', 'Informativo'), ('yes_no', 'Sim/Não'), ('multiple_choice', 'Múltipla Escolha'), ('checklist', 'Checklist com Regra de Avanço'), ('numeric_input', 'Input Numérico'), ('derived_calc', 'Cálculo Derivado'), ('medication_prescription', 'Prescrição de Medicação'), ('wait_reassess', 'Aguardar/Reavaliar'), ('titration_loop', 'Loop de Titulação')], max_length=25, verbose_name='Tipo do passo'),
        ),
    ]
