# Generated by Django 6.0.4 on 2026-05-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_alter_protocolstep_step_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolexecution',
            name='current_step_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID declarativo do passo atual'),
        ),
        migrations.AddField(
            model_name='protocolexecutionstate',
            name='step_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID declarativo do passo'),
        ),
        migrations.AlterField(
            model_name='protocolexecutionstate',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_states', to='protocols.protocolstep', verbose_name='Passo'),
        ),
    ]
