# Generated by Django 6.0.4 on 2026-06-18 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_data_alta_paciente_status'),
        ('protocols', '0009_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolexecution',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_executions', to='pacientes.paciente', verbose_name='Paciente'),
        ),
    ]
